language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.5.5
  - DJANGO=1.6.2
install:
  - pip install -q Django==$DJANGO
  - pip install -q pycrypto psycopg2
script:
  - python setup.py test
before_script:
  - psql -c 'create database citadel;' -U postgres
